name: sdmx
description: Fetch records from SDMX servers. Parse them into a Dart readable SDMXModel object. Filter with ease using SDMXRecordEntry objects.
version: 1.0.3
repository: https://github.com/sohaibbg/sdmx

environment:
  sdk: ^3.5.0

dependencies:
  http: ^1.2.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
